Repository prgrms-web-devcourse/Team-Books-CheckMoi-BE, pull requests merged in 2022-08, with the labels that each got.

#54 ✨ feat : 스터디 참가 신청 기능 구현
  src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/DuplicateStudyJoinRequestException.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/StudyMember.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/StudyMemberRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/global/exception/DuplicateException.java
  src/main/java/com/devcourse/checkmoi/global/exception/ErrorMessage.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/stub/StudyMemberStub.java
  src/test/java/com/devcourse/checkmoi/domain/study/stub/StudyStub.java
Labels: ✨ feat, study

#59 ♻️ refactor : 유저 스터디 조회
  src/main/java/com/devcourse/checkmoi/domain/user/api/UserApi.java
  src/main/java/com/devcourse/checkmoi/domain/user/converter/UserConverter.java
  src/main/java/com/devcourse/checkmoi/domain/user/dto/UserResponse.java
  src/main/java/com/devcourse/checkmoi/domain/user/dto/UserStudyResponse.java
  src/main/java/com/devcourse/checkmoi/domain/user/model/UserRole.java
  src/main/java/com/devcourse/checkmoi/domain/user/repository/CustomUserRepository.java
  src/main/java/com/devcourse/checkmoi/domain/user/repository/CustomUserRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/user/repository/UserRepository.java
  src/main/java/com/devcourse/checkmoi/domain/user/service/UserQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/user/service/UserQueryServiceImpl.java
  src/main/java/com/devcourse/checkmoi/global/security/oauth/UserProfile.java
  src/test/java/com/devcourse/checkmoi/domain/study/repository/study/StudyRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/user/stub/UserStub.java
Labels: ♻️ refactor, user

#61 🔧 chore : 서버 RDS datasource 설정
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 🔧 chore

#69 ♻️ refactor : 스터디 정보 수정에 상태 변경도 가능하도록 변경
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImplTest.java
Labels: ✨ feat

#72 🐛 fix : 스터디 수정에서 스터디 장을 불러올때 null이 넘어오는 현상 해결
  .github/workflows/deploy-dev.yaml
  .github/workflows/deploy-prod.yaml
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
Labels: 🐛 fix, study

#77 ♻️ refactor : 회원 정보 조회 API 변경
  src/main/java/com/devcourse/checkmoi/domain/user/api/UserApi.java
  src/main/java/com/devcourse/checkmoi/global/security/handler/OAuthAuthenticationSuccessHandler.java
  src/test/java/com/devcourse/checkmoi/domain/user/api/UserIntegrationTest.java
Labels: ♻️ refactor

#75 ✨ feat : API 호출 로깅
  build.gradle
  src/main/java/com/devcourse/checkmoi/domain/user/api/AuthApi.java
  src/main/java/com/devcourse/checkmoi/global/aop/ControllerLoggingAspect.java
Labels: 🔧 chore, ✨ feat

#79 ✨ feat : 스터디 상세 조회
  src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/StudyMember.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyQueryServiceImpl.java
  src/main/resources/application-security.yml
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/repository/study/StudyRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/util/EntityGeneratorUtil.java
Labels: ✨ feat

#78 ✨ feat : S3 이미지 업로드
  .github/workflows/ci.yaml
  .github/workflows/deploy-dev.yaml
  build.gradle
  src/main/java/com/devcourse/checkmoi/domain/file/api/ImageApi.java
  src/main/java/com/devcourse/checkmoi/domain/file/dto/AttachedFileRequest.java
  src/main/java/com/devcourse/checkmoi/domain/file/dto/AttachedFileResponse.java
  src/main/java/com/devcourse/checkmoi/domain/file/exception/NotAllowedFileException.java
  src/main/java/com/devcourse/checkmoi/domain/file/model/Domain.java
  src/main/java/com/devcourse/checkmoi/domain/file/model/FileUploaded.java
  src/main/java/com/devcourse/checkmoi/domain/file/model/vo/AttachedFile.java
  src/main/java/com/devcourse/checkmoi/domain/file/repository/FileUploadedRepository.java
  src/main/java/com/devcourse/checkmoi/domain/file/service/FileService.java
  src/main/java/com/devcourse/checkmoi/domain/file/service/FileServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/file/service/S3Upload.java
  src/main/java/com/devcourse/checkmoi/global/config/AwsConfigProperties.java
  src/main/java/com/devcourse/checkmoi/global/config/WebConfig.java
  src/main/java/com/devcourse/checkmoi/global/exception/BusinessException.java
  src/main/java/com/devcourse/checkmoi/global/exception/ErrorMessage.java
  src/main/resources/application-aws.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/devcourse/checkmoi/domain/file/api/ImageApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/file/model/vo/AttachedFileTest.java
  src/test/java/com/devcourse/checkmoi/domain/file/repository/FileUploadedRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/file/service/FileServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/file/service/S3UploadTest.java
  src/test/java/com/devcourse/checkmoi/domain/file/service/img.png
Labels: ✨ feat

#84 🐛 fix : 환경변수 설정을 추가한다 (#83)
  .github/workflows/deploy-dev.yaml
  .github/workflows/deploy-prod.yaml
  src/main/resources/application-aws.yml
  src/main/resources/application.yml
Labels: 🐛 bug

#85 ✨ feat : 유저 온도 정보 추가
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/token/api/TokenApi.java
  src/main/java/com/devcourse/checkmoi/domain/token/service/TokenService.java
  src/main/java/com/devcourse/checkmoi/domain/user/converter/UserConverter.java
  src/main/java/com/devcourse/checkmoi/domain/user/dto/UserResponse.java
  src/main/java/com/devcourse/checkmoi/domain/user/model/User.java
  src/main/java/com/devcourse/checkmoi/domain/user/repository/CustomUserRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/global/security/config/SecurityConfig.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/token/api/TokenApiTest.java
  src/test/java/com/devcourse/checkmoi/util/EntityGeneratorUtil.java
Labels: ✨ feat

#91 ♻️refactor : 책 목록 반환시 반환 값 수정
  src/main/java/com/devcourse/checkmoi/domain/book/converter/BookConverter.java
  src/main/java/com/devcourse/checkmoi/domain/book/dto/BookResponse.java
  src/main/java/com/devcourse/checkmoi/domain/book/dto/SimplePage.java
  src/main/java/com/devcourse/checkmoi/domain/book/repository/BookRepository.java
  src/main/java/com/devcourse/checkmoi/domain/book/repository/CustomBookRepository.java
  src/main/java/com/devcourse/checkmoi/domain/book/repository/CustomBookRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/book/service/BookQueryServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/converter/BookConverterTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/repository/BookRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/service/BookQueryServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/stub/NewDummyData.java
  src/test/java/com/devcourse/checkmoi/domain/book/stub/PersistedDummyData.java
  src/test/java/com/devcourse/checkmoi/domain/study/stub/StudyStub.java
Labels: book

#93 ✨ feat : 스터디 신청목록 확인
  src/main/java/com/devcourse/checkmoi/domain/file/api/ImageApi.java
  src/main/java/com/devcourse/checkmoi/domain/file/model/vo/AttachedFile.java
  src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyQueryServiceImpl.java
  src/test/java/com/devcourse/checkmoi/domain/file/api/ImageApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/repository/study/StudyRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyQueryServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/util/EntityGeneratorUtil.java
Labels: ✨ feat

#99 ♻️ refactor : 책제목 길이 수정
  src/main/java/com/devcourse/checkmoi/domain/book/model/Book.java
Labels: ♻️ refactor

#112 ✨ feat : 스터디 상태를 진행중으로 상태변경시 스터디신청목록 처리
  src/main/java/com/devcourse/checkmoi/domain/study/converter/StudyConverter.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/NotAllowedStudyStatusException.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/StudyStatus.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/global/exception/ErrorMessage.java
  src/test/java/com/devcourse/checkmoi/domain/study/converter/StudyConverterTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/model/StudyStatusTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/model/StudyTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/repository/study/StudyRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/stub/StudyStub.java
  src/test/java/com/devcourse/checkmoi/util/EntityGeneratorUtil.java
Labels: ✨ feat

#100 ♻️ refactor : 반환되는 책 정보 추가
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
Labels: ♻️ refactor

#117 ✨ feat : ISBN을 기준으로 책 조회기능 추가
  src/main/java/com/devcourse/checkmoi/domain/book/api/BookApi.java
  src/main/java/com/devcourse/checkmoi/domain/book/service/BookQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/book/service/BookQueryServiceImpl.java
  src/main/java/com/devcourse/checkmoi/global/security/handler/OAuthAuthenticationSuccessHandler.java
  src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/service/BookQueryServiceImplTest.java
Labels: ✨ feat, book

#121 ✨ feat : Date를 받을 경우 추가적으로 역직렬화 처리를 해주도록 구현
  src/main/java/com/devcourse/checkmoi/global/config/JacksonDeserializeConfig.java
Labels: ✨ feat

#123 🔧 chore : 사용 포트 추가
  src/main/java/com/devcourse/checkmoi/global/config/WebConfig.java
Labels: 🔧 chore

#126 ✨ feat : 게시글 , 커멘트 도메인 초기 설정
  src/main/java/com/devcourse/checkmoi/domain/comment/model/Comment.java
  src/main/java/com/devcourse/checkmoi/domain/post/model/Post.java
  src/main/java/com/devcourse/checkmoi/domain/post/model/PostCategory.java
  src/test/java/com/devcourse/checkmoi/domain/comment/model/CommentTest.java
  src/test/java/com/devcourse/checkmoi/domain/post/model/PostTest.java
  src/test/java/com/devcourse/checkmoi/util/EntityGeneratorUtil.java
Labels: ✨ feat

#135 ♻️ refactor : 게시글 DTO 리팩토링
  src/main/java/com/devcourse/checkmoi/domain/comment/api/CommentApi.java
  src/main/java/com/devcourse/checkmoi/domain/comment/converter/CommentConverter.java
  src/main/java/com/devcourse/checkmoi/domain/comment/dto/CommentRequest.java
  src/main/java/com/devcourse/checkmoi/domain/comment/service/CommentQueryServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/post/api/PostApi.java
  src/main/java/com/devcourse/checkmoi/domain/post/converter/PostConverter.java
  src/main/java/com/devcourse/checkmoi/domain/post/dto/PostRequest.java
  src/main/java/com/devcourse/checkmoi/domain/post/dto/PostResponse.java
  src/main/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepository.java
  src/main/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/post/service/PostQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/post/service/PostQueryServiceImpl.java
  src/test/java/com/devcourse/checkmoi/domain/comment/service/CommentQueryServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/post/api/PostApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/post/converter/PostConverterTest.java
  src/test/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepositoryImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/post/service/PostQueryServiceImplTest.java
Labels: ♻️ refactor, post

#132 ✨ feat : 내 스터디 목록 조회
  src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
  src/main/java/com/devcourse/checkmoi/domain/study/facade/StudyUserFacade.java
  src/main/java/com/devcourse/checkmoi/domain/study/facade/StudyUserFacadeImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/facade/StudyUserFacadeImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/util/DTOGeneratorUtil.java
Labels: ✨ feat, study

#140 ✨ feat : 게시글 작성 서비스로직 권한검증 기능 추가 (#134)
  src/main/java/com/devcourse/checkmoi/domain/book/api/BookApi.java
  src/main/java/com/devcourse/checkmoi/domain/post/exception/NotAllowedWriterException.java
  src/main/java/com/devcourse/checkmoi/domain/post/model/PostCategory.java
  src/main/java/com/devcourse/checkmoi/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/StudyMemberRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/global/exception/ErrorMessage.java
  src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/post/service/PostCommandServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImplTest.java
Labels: ✨ feat

#141 🔧 chore : flyway 기능 적용
  build.gradle
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/db/migration/V1_0__INIT.sql
Labels: 🔧 chore

#153 ♻️ refactor : Post 데이터 필드 네이밍 변경 (#150)
  src/main/java/com/devcourse/checkmoi/domain/post/converter/PostConverter.java
  src/main/java/com/devcourse/checkmoi/domain/post/dto/PostResponse.java
  src/test/java/com/devcourse/checkmoi/domain/post/api/PostApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/post/converter/PostConverterTest.java
  src/test/java/com/devcourse/checkmoi/domain/post/service/PostQueryServiceImplTest.java
Labels: ♻️ refactor

#145 ✨ feat : 댓글 작성 기능 추가
  src/main/java/com/devcourse/checkmoi/domain/comment/api/CommentApi.java
  src/main/java/com/devcourse/checkmoi/domain/comment/converter/CommentConverter.java
  src/main/java/com/devcourse/checkmoi/domain/comment/dto/CommentRequest.java
  src/main/java/com/devcourse/checkmoi/domain/comment/facade/CommentCommandFacade.java
  src/main/java/com/devcourse/checkmoi/domain/comment/facade/CommentCommandFacadeImpl.java
  src/main/java/com/devcourse/checkmoi/domain/comment/service/CommentCommandService.java
  src/main/java/com/devcourse/checkmoi/domain/comment/service/CommentCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/FinishedStudyException.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/NotAllowedStudyStatusException.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/NotParticipateStudyUserException.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyMemberRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyMemberRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/StudyMemberRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyServiceValidator.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyServiceValidatorImpl.java
  src/main/java/com/devcourse/checkmoi/global/exception/ErrorMessage.java
  src/main/java/com/devcourse/checkmoi/global/exception/InvalidStatusException.java
  src/test/java/com/devcourse/checkmoi/domain/comment/api/CommentApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/comment/facade/CommentCommandFacadeImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/comment/service/CommentCommandServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyMemberRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/validator/StudyServiceValidatorImplTest.java
  src/test/java/com/devcourse/checkmoi/util/DTOGeneratorUtil.java
Labels: ✨ feat, comment

#157 ♻️ refactor : 패키지 구조 리팩토링
  build.gradle
  src/main/java/com/devcourse/checkmoi/domain/book/exception/BookNotFoundException.java
  src/main/java/com/devcourse/checkmoi/domain/file/exception/NotAllowedFileException.java
  src/main/java/com/devcourse/checkmoi/domain/post/exception/NotAllowedWriterException.java
  src/main/java/com/devcourse/checkmoi/domain/post/exception/PostNoPermissionException.java
  src/main/java/com/devcourse/checkmoi/domain/post/exception/PostNotFoundException.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/DuplicateStudyJoinRequestException.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/FinishedStudyException.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/NotAllowedStudyStatusException.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/NotParticipateStudyUserException.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/NotStudyOwnerException.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/StudyJoinRequestNotFoundException.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/StudyNotFoundException.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyServiceValidatorImpl.java
  src/main/java/com/devcourse/checkmoi/domain/token/api/TokenApi.java
  src/main/java/com/devcourse/checkmoi/domain/token/service/TokenService.java
  src/main/java/com/devcourse/checkmoi/domain/user/api/AuthApi.java
  src/main/java/com/devcourse/checkmoi/domain/user/exception/UserNoPermissionException.java
  src/main/java/com/devcourse/checkmoi/domain/user/model/UserRole.java
  src/main/java/com/devcourse/checkmoi/global/config/AWSConfig.java
  src/main/java/com/devcourse/checkmoi/global/config/StaticRoutingConfigure.java
  src/main/java/com/devcourse/checkmoi/global/config/WebConfig.java
  src/main/java/com/devcourse/checkmoi/global/config/property/AwsConfigProperties.java
  src/main/java/com/devcourse/checkmoi/global/config/property/CorsConfigProperties.java
  src/main/java/com/devcourse/checkmoi/global/exception/BusinessException.java
  src/main/java/com/devcourse/checkmoi/global/exception/DuplicateException.java
  src/main/java/com/devcourse/checkmoi/global/exception/EntityNotFoundException.java
  src/main/java/com/devcourse/checkmoi/global/exception/InvalidStatusException.java
  src/main/java/com/devcourse/checkmoi/global/exception/InvalidValueException.java
  src/main/java/com/devcourse/checkmoi/global/exception/error/Error.java
  src/main/java/com/devcourse/checkmoi/global/exception/error/ErrorField.java
  src/main/java/com/devcourse/checkmoi/global/exception/error/ErrorMessage.java
  src/main/java/com/devcourse/checkmoi/global/exception/error/ErrorResponse.java
  src/main/java/com/devcourse/checkmoi/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/devcourse/checkmoi/global/security/config/SecurityConfig.java
  src/main/java/com/devcourse/checkmoi/global/security/config/property/SecurityConfigProperties.java
  src/main/java/com/devcourse/checkmoi/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/devcourse/checkmoi/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/devcourse/checkmoi/global/security/jwt/JwtAuthenticationToken.java
  src/main/java/com/devcourse/checkmoi/global/security/jwt/exception/ExpiredTokenException.java
  src/main/java/com/devcourse/checkmoi/global/security/jwt/exception/InvalidTokenException.java
  src/main/java/com/devcourse/checkmoi/global/security/jwt/exception/TokenException.java
  src/main/java/com/devcourse/checkmoi/global/security/jwt/exception/handler/ExceptionHandlerFilter.java
  src/main/java/com/devcourse/checkmoi/global/security/jwt/util/AuthorizationExtractor.java
  src/main/java/com/devcourse/checkmoi/global/security/oauth/handler/OAuthAuthenticationSuccessHandler.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-security.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImplTest.java
Labels: 🔧 chore

#160 ✨ feat : 스터디 조회 API v2
  build.gradle
  src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
  src/main/java/com/devcourse/checkmoi/global/model/PageRequest.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyRepositoryTest.java
Labels: ✨ feat

#161 ♻️ refactor : study 리스트 조회에 대해서 페이징 적용
  build.gradle
  src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/facade/StudyUserFacadeImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/util/DTOGeneratorUtil.java
Labels: ♻️ refactor, study

#169 ✨ feat : 스터디에 모집완료 상태 추가 에 따른 상태 변경 제약 로직 수정 및 테스트 (#168)
  src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/StudyStatus.java
  src/test/java/com/devcourse/checkmoi/domain/study/model/StudyStatusTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/model/StudyTest.java
Labels: ✨ feat, study

#186 ✨ feat : 책검색 API v2
  src/main/java/com/devcourse/checkmoi/domain/book/api/BookApi.java
  src/main/java/com/devcourse/checkmoi/domain/book/converter/BookConverter.java
  src/main/java/com/devcourse/checkmoi/domain/book/dto/BookRequest.java
  src/main/java/com/devcourse/checkmoi/domain/book/dto/BookResponse.java
  src/main/java/com/devcourse/checkmoi/domain/book/repository/CustomBookRepository.java
  src/main/java/com/devcourse/checkmoi/domain/book/repository/CustomBookRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/book/service/BookCommandService.java
  src/main/java/com/devcourse/checkmoi/domain/book/service/BookCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/book/service/BookQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/book/service/BookQueryServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
  src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/converter/BookConverterTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/repository/BookRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/service/BookCommandServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/service/BookQueryServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/stub/NewDummyData.java
  src/test/java/com/devcourse/checkmoi/domain/book/stub/PersistedDummyData.java
  src/test/java/com/devcourse/checkmoi/domain/post/api/PostApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/user/api/UserIntegrationTest.java
Labels: 📝 docs, ✨ feat, ⚙️ test, book

#187 ♻️ refactor : 댓글 수정 validate 추가
  src/main/java/com/devcourse/checkmoi/domain/comment/api/CommentApi.java
  src/main/java/com/devcourse/checkmoi/domain/comment/exception/CommentNoPermissionException.java
  src/main/java/com/devcourse/checkmoi/domain/comment/facade/CommentCommandFacade.java
  src/main/java/com/devcourse/checkmoi/domain/comment/facade/CommentCommandFacadeImpl.java
  src/main/java/com/devcourse/checkmoi/domain/comment/facade/CommentFacade.java
  src/main/java/com/devcourse/checkmoi/domain/comment/facade/CommentQueryFacade.java
  src/main/java/com/devcourse/checkmoi/domain/comment/service/CommentCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/comment/service/validator/CommentValidator.java
  src/main/java/com/devcourse/checkmoi/domain/comment/service/validator/CommentValidatorImpl.java
  src/main/java/com/devcourse/checkmoi/global/exception/InvalidAuthorizeException.java
  src/main/java/com/devcourse/checkmoi/global/exception/error/ErrorMessage.java
  src/test/java/com/devcourse/checkmoi/domain/comment/api/CommentApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/comment/facade/CommentCommandFacadeImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/comment/facade/CommentFacadeTest.java
  src/test/java/com/devcourse/checkmoi/domain/comment/service/CommentCommandServiceImplTest.java
Labels: ♻️ refactor, comment

#188 ✨ feat : 모집기간이 만료된 스터디 상태를 변경하는 스케줄러 등록
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyCommandService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/dto/ExpiredStudies.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/schedule/StudyScheduleService.java
  src/main/java/com/devcourse/checkmoi/global/config/SchedulerConfig.java
  src/main/java/com/devcourse/checkmoi/global/scheduler/ScheduleManager.java
  src/main/java/com/devcourse/checkmoi/global/scheduler/Scheduler.java
  src/main/resources/application.yml
  src/test/java/com/devcourse/checkmoi/domain/study/service/schedule/StudyScheduleServiceTest.java
  src/test/java/com/devcourse/checkmoi/util/EntityGeneratorUtil.java
Labels: ✨ feat, study

#191 ♻️ refactor : API 문서화 및 enum 소문자로 받도록 구현
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImpl.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
Labels: ♻️ refactor, study

#194 ♻️ refactor : 댓글 삭제 기능에 대한 validation 추가
  src/main/java/com/devcourse/checkmoi/domain/comment/facade/CommentFacade.java
  src/main/java/com/devcourse/checkmoi/domain/comment/service/CommentCommandService.java
  src/main/java/com/devcourse/checkmoi/domain/comment/service/CommentCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/comment/service/validator/CommentValidator.java
  src/main/java/com/devcourse/checkmoi/domain/comment/service/validator/CommentValidatorImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidator.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidatorImpl.java
  src/test/java/com/devcourse/checkmoi/domain/comment/api/CommentApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/comment/facade/CommentFacadeTest.java
  src/test/java/com/devcourse/checkmoi/domain/comment/service/CommentCommandServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidatorImplTest.java
Labels: ♻️ refactor, comment

#201 ♻️ refactor : 스터디신청승인
  src/main/java/com/devcourse/checkmoi/domain/comment/facade/CommentFacade.java
  src/main/java/com/devcourse/checkmoi/domain/comment/service/CommentCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomRepositoryUtil.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/StudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidator.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidatorImpl.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidatorImplTest.java
Labels: ♻️ refactor

#203 ♻️ refactor : 스터디 승인/거절 기능 validation 추가
  src/main/java/com/devcourse/checkmoi/domain/study/exception/NotRecruitingStudyException.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/StudyMemberFullException.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidator.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidatorImpl.java
  src/main/java/com/devcourse/checkmoi/global/exception/error/ErrorMessage.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidatorImplTest.java
Labels: ♻️ refactor, study

#207 ♻️ refactor : 댓글 목록 조회시 작성자 이름과 프로필 이미지를 포함해서 보내도록 변경
  src/main/java/com/devcourse/checkmoi/domain/comment/dto/CommentResponse.java
  src/main/java/com/devcourse/checkmoi/domain/comment/repository/CustomCommentRepositoryImpl.java
  src/test/java/com/devcourse/checkmoi/domain/comment/api/CommentApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/comment/service/CommentQueryServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/util/DTOGeneratorUtil.java
Labels: ♻️ refactor, comment

#209 ✨ feat : 게시글 정보 글쓴이 아이디 추가
  src/main/java/com/devcourse/checkmoi/domain/post/converter/PostConverter.java
  src/main/java/com/devcourse/checkmoi/domain/post/dto/PostResponse.java
  src/main/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepositoryImpl.java
  src/test/java/com/devcourse/checkmoi/domain/post/api/PostApiTest.java
Labels: ✨ feat

#206 ✨ feat : 게시글 목록 불러오기 페이지네이션으로 변경
  src/main/java/com/devcourse/checkmoi/domain/post/api/PostApi.java
  src/main/java/com/devcourse/checkmoi/domain/post/dto/PostRequest.java
  src/main/java/com/devcourse/checkmoi/domain/post/dto/PostResponse.java
  src/main/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepository.java
  src/main/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/post/service/PostQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/post/service/PostQueryServiceImpl.java
  src/main/java/com/devcourse/checkmoi/global/model/SimplePage.java
  src/test/java/com/devcourse/checkmoi/domain/post/api/PostApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepositoryImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/post/service/PostQueryServiceImplTest.java
Labels: ✨ feat, post

#211 🔧 chore : v2 GET 메소드 권한 수정
  src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
  src/main/resources/application-security.yml
  src/main/resources/application-test.yml
  src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyRepositoryTest.java
Labels: 🔧 chore

#213 🔧 chore : 서버 Cache 전략 변경
  src/main/java/com/devcourse/checkmoi/global/config/WebConfig.java
Labels: 🔧 chore

#215 📝 docs : 토큰 스웨거 문서 추가
  src/test/java/com/devcourse/checkmoi/domain/token/api/TokenApiTest.java
Labels: 📝 docs

#216 ✨ feat : 특정한 문자열을 입출력하는 열거타입 정의 (#202)
  src/main/java/com/devcourse/checkmoi/domain/book/dto/BookRequest.java
  src/main/java/com/devcourse/checkmoi/domain/post/dto/PostRequest.java
  src/main/java/com/devcourse/checkmoi/domain/post/model/PostCategory.java
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/StudyMemberStatus.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/StudyStatus.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/global/annotation/CodeMappable.java
  src/main/java/com/devcourse/checkmoi/global/annotation/ValueOfEnum.java
  src/main/java/com/devcourse/checkmoi/global/annotation/ValueOfEnumValidator.java
  src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/repository/BookRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/post/service/PostCommandServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImplTest.java
Labels: ✨ feat, book, study, post

#219 ✨ feat : 이미지 용량 초과 예외메시지 추가 (#173)
  src/main/java/com/devcourse/checkmoi/global/exception/error/ErrorMessage.java
  src/main/java/com/devcourse/checkmoi/global/exception/handler/GlobalExceptionHandler.java
Labels: image

#225 ✨ feat : 진행기간이 지난 스터디들을 진행완료상태로 변경하는 기능 추가 (#173)
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/schedule/StudyScheduleService.java
  src/main/java/com/devcourse/checkmoi/global/scheduler/ScheduleManager.java
  src/main/java/com/devcourse/checkmoi/global/scheduler/Scheduler.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/schedule/StudyScheduleServiceTest.java
Labels: ✨ feat

#232 ♻️ refactor : 스터디 상태 크론 시간 변경
  src/main/java/com/devcourse/checkmoi/global/scheduler/Scheduler.java
Labels: :zap: simple

#234 🐛 fix : 페이지네이션을 통해 totalPage 가져오는 부분 변경 (#233)
  src/main/java/com/devcourse/checkmoi/domain/post/dto/PostResponse.java
  src/main/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepository.java
  src/main/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/post/service/PostQueryServiceImpl.java
  src/test/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepositoryImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/post/service/PostQueryServiceImplTest.java
Labels: post

#236 ♻️ refactor : 토큰 타입별 에러메시지 분리
  src/main/java/com/devcourse/checkmoi/global/exception/error/ErrorMessage.java
  src/main/java/com/devcourse/checkmoi/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/devcourse/checkmoi/global/security/jwt/exception/ExpiredAccessTokenException.java
  src/main/java/com/devcourse/checkmoi/global/security/jwt/exception/ExpiredRefreshTokenException.java
  src/main/java/com/devcourse/checkmoi/global/security/jwt/exception/ExpiredTokenException.java
Labels: ♻️ refactor

#248 📝 docs : 리드미 수정 2
  README.md
Labels: 📝 docs

#251 ✨ feat : 로그인 사용자를 로그에 출력하도록 logback 설정
  intellij-java-checkmoi-style.xml
  src/main/java/com/devcourse/checkmoi/global/log/AuthToMdcFilter.java
  src/main/java/com/devcourse/checkmoi/global/log/aop/ControllerLoggingAspect.java
  src/main/resources/logback.xml
Labels: 🎨 style

#253 ✨ feat : 스케줄러 동작 api 추가 (#252)
  build.gradle
  src/main/java/com/devcourse/checkmoi/domain/study/api/ScheduleApi.java
  src/main/java/com/devcourse/checkmoi/global/scheduler/Scheduler.java
  src/test/java/com/devcourse/checkmoi/global/scheduler/SchedulerTest.java
Labels: study

#256 🚀 release : CheckMoi v3.1.0
  build.gradle
  src/main/java/com/devcourse/checkmoi/domain/book/converter/BookConverter.java
  src/main/java/com/devcourse/checkmoi/domain/book/dto/BookResponse.java
  src/main/java/com/devcourse/checkmoi/domain/study/api/ScheduleApi.java
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
  src/main/java/com/devcourse/checkmoi/global/scheduler/Scheduler.java
  src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/converter/BookConverterTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/stub/NewDummyData.java
  src/test/java/com/devcourse/checkmoi/domain/book/stub/PersistedDummyData.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/global/scheduler/SchedulerTest.java
  src/test/java/com/devcourse/checkmoi/util/DTOGeneratorUtil.java
Labels: 🚀 release
