Repository prgrms-web-devcourse/Team-Books-CheckMoi-BE, pull requests merged in 2022-07, with the labels that each got.

#8 🎉 init : 프로젝트 초기 설정
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/devcourse/checkmoi/CheckmoiApplication.java
  src/main/resources/application.properties
  src/test/java/com/devcourse/checkmoi/CheckmoiApplicationTests.java
Labels: 🎉 init

#12 📝 docs : 문서 템플릿 설정
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
Labels: 📝 docs

#17 ✨ feat : api 응답에 대한 공동 객체 정의 및 BusinessException 정의 추가
  src/main/java/com/devcourse/checkmoi/global/exception/BusinessException.java
  src/main/java/com/devcourse/checkmoi/global/exception/EntityNotFoundException.java
  src/main/java/com/devcourse/checkmoi/global/exception/Error.java
  src/main/java/com/devcourse/checkmoi/global/exception/ErrorField.java
  src/main/java/com/devcourse/checkmoi/global/exception/ErrorMessage.java
  src/main/java/com/devcourse/checkmoi/global/exception/ErrorResponse.java
  src/main/java/com/devcourse/checkmoi/global/exception/GlobalExceptionHandler.java
  src/main/java/com/devcourse/checkmoi/global/exception/InvalidValueException.java
  src/main/java/com/devcourse/checkmoi/global/model/SuccessResponse.java
  src/main/resources/application.yml
Labels: ✨ feat

#20 🔧 chore : CI/CD 설정
  .github/workflows/ci.yaml
  .github/workflows/deploy-dev.yaml
  .github/workflows/deploy-prod.yaml
  build.gradle
Labels: 🚀 ci/cd

#22 🧪 test : 테스트 기본 템플릿 설정
  src/test/java/com/devcourse/checkmoi/config/QueryConfig.java
  src/test/java/com/devcourse/checkmoi/template/ApiTest.java
  src/test/java/com/devcourse/checkmoi/template/RepositoryTest.java
  src/test/java/com/devcourse/checkmoi/util/DocumentUtil.java
Labels: ⚙️ test

#24 🔧 chore : API 문서 제공을 위한 RestDocs 작성 및 Swagger 변환 자동화 구현
  .github/workflows/deploy-dev.yaml
  .github/workflows/deploy-prod.yaml
  .gitignore
  build.gradle
  src/main/java/com/devcourse/checkmoi/global/config/StaticRoutingConfigure.java
  src/main/resources/static/docs/favicon-16x16.png
  src/main/resources/static/docs/favicon-32x32.png
  src/main/resources/static/docs/index.css
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/swagger-initializer.js
  src/main/resources/static/docs/swagger-ui-bundle.js
  src/main/resources/static/docs/swagger-ui-bundle.js.map
  src/main/resources/static/docs/swagger-ui-es-bundle-core.js.map
  src/main/resources/static/docs/swagger-ui-es-bundle.js.map
  src/main/resources/static/docs/swagger-ui-standalone-preset.js
  src/main/resources/static/docs/swagger-ui-standalone-preset.js.map
  src/main/resources/static/docs/swagger-ui.css
  src/main/resources/static/docs/swagger-ui.css.map
  src/main/resources/static/docs/swagger-ui.js.map
Labels: 🔧 chore

#26 🐛 fix : 자동 배포중 Export로 서버 네임 지정하는 구문 에러 발생
  .github/workflows/deploy-dev.yaml
  .github/workflows/deploy-prod.yaml
Labels: 🐛 fix

#29 ✨ feat : 스터디 생성 기능 구현
  build.gradle
  src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
  src/main/java/com/devcourse/checkmoi/domain/study/converter/StudyConverter.java
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/StudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/converter/StudyConverterTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImplTest.java
Labels: ✨ feat

#34 🐛 fix : 삭제한 파일 복구 및 파일 내용 수정
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/deploy-dev.yaml
  .github/workflows/deploy-prod.yaml
Labels: 🐛 fix

#38 ✨ feat : 스터디 정보 수정
  src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/NotStudyOwnerException.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/StudyNotFoundException.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/StudyMember.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/StudyMemberRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/StudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/global/exception/ErrorMessage.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/repository/study/StudyRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImplTest.java
Labels: ✨ feat

#39 ✨ feat : 책을 관리한다
  src/main/java/com/devcourse/checkmoi/domain/book/api/BookApi.java
  src/main/java/com/devcourse/checkmoi/domain/book/converter/BookConverter.java
  src/main/java/com/devcourse/checkmoi/domain/book/dto/BookRequest.java
  src/main/java/com/devcourse/checkmoi/domain/book/dto/BookResponse.java
  src/main/java/com/devcourse/checkmoi/domain/book/dto/SimplePage.java
  src/main/java/com/devcourse/checkmoi/domain/book/exception/BookNotFoundException.java
  src/main/java/com/devcourse/checkmoi/domain/book/model/Book.java
  src/main/java/com/devcourse/checkmoi/domain/book/repository/BookRepository.java
  src/main/java/com/devcourse/checkmoi/domain/book/service/BookCommandService.java
  src/main/java/com/devcourse/checkmoi/domain/book/service/BookCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/book/service/BookQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/book/service/BookQueryServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/StudyMember.java
  src/main/java/com/devcourse/checkmoi/global/exception/ErrorMessage.java
  src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/converter/BookConverterTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/dto/SimplePageTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/model/BookTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/model/PublishedDateTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/repository/BookRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/service/BookCommandServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/service/BookQueryServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/book/stub/NewDummyData.java
  src/test/java/com/devcourse/checkmoi/domain/book/stub/PersistedDummyData.java
  src/test/java/com/devcourse/checkmoi/domain/study/repository/study/StudyRepositoryTest.java
Labels: ✨ feat

#41 ✨ feat : 스터디 가입 승낙 및 거절
  src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/StudyJoinRequestNotFoundException.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/StudyMember.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/global/exception/ErrorMessage.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImplTest.java
Labels: ✨ feat, study

#47 📝 docs : PR 템플릿 변경
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 docs, :zap: simple

#44 ✨ feat : 유저를 관리한다
  src/main/java/com/devcourse/checkmoi/domain/book/model/Book.java
  src/main/java/com/devcourse/checkmoi/domain/study/exception/NotStudyOwnerException.java
  src/main/java/com/devcourse/checkmoi/domain/token/api/TokenApi.java
  src/main/java/com/devcourse/checkmoi/domain/user/api/UserApi.java
  src/main/java/com/devcourse/checkmoi/domain/user/dto/UserRequest.java
  src/main/java/com/devcourse/checkmoi/domain/user/exception/UserNoPermissionException.java
  src/main/java/com/devcourse/checkmoi/domain/user/model/User.java
  src/main/java/com/devcourse/checkmoi/domain/user/service/UserCommandService.java
  src/main/java/com/devcourse/checkmoi/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/user/service/UserQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/user/service/UserQueryServiceImpl.java
  src/main/java/com/devcourse/checkmoi/global/security/config/SecurityConfig.java
  src/main/java/com/devcourse/checkmoi/global/security/oauth/OAuthService.java
  src/main/resources/application-security.yml
  src/test/java/com/devcourse/checkmoi/domain/token/api/TokenApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/user/api/UserIntegrationTest.java
  src/test/java/com/devcourse/checkmoi/template/ApiTest.java
  src/test/java/com/devcourse/checkmoi/template/IntegrationTest.java
Labels: 📝 docs, ♻️ refactor

#49 ✨ feat : 특정 책에 대한 스터디 목록 조회
  src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
  src/main/java/com/devcourse/checkmoi/domain/study/converter/StudyConverter.java
  src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
  src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepositoryImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/repository/study/StudyMemberRepository.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyQueryService.java
  src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyQueryServiceImpl.java
  src/main/java/com/devcourse/checkmoi/global/model/PageRequest.java
  src/main/java/com/devcourse/checkmoi/global/security/config/SecurityConfig.java
  src/test/java/com/devcourse/checkmoi/domain/book/stub/BookStub.java
  src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/repository/study/StudyRepositoryTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyQueryServiceImplTest.java
  src/test/java/com/devcourse/checkmoi/domain/study/stub/StudyMemberStub.java
  src/test/java/com/devcourse/checkmoi/domain/study/stub/StudyStub.java
  src/test/java/com/devcourse/checkmoi/domain/user/stub/UserStub.java
  src/test/java/com/devcourse/checkmoi/template/RepositoryTest.java
Labels: ✨ feat, study
